def BRANCH = ""
def version = ""
def appName = ""

pipeline {

	agent { label "debian" }
	tools {
        maven 'maven-360' 
    }
	stages {

		stage ("Inicializacion") {
            steps {
				echo "Inicio pipeline"
            }
        }

        stage ("artifactId y version desde el pom.xml") {
            steps {
            	script {
    				version = sh script: 'mvn help:evaluate -Dexpression=project.version -q -DforceStdout', returnStdout: true
    				appName = sh script: 'mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout', returnStdout: true
    				BRANCH = BRANCH_NAME.substring(BRANCH_NAME.lastIndexOf('/') + 1, BRANCH_NAME.length())
            	}
            }
        }

        stage ("Echo variables") {
            steps {
				echo "version = ${version}"
				echo "appName = ${appName}"
				echo "BRANCH_NAME = ${BRANCH}"
            }
        }

        stage("deploy") {
        	steps {
				script {
					echo "desplegando"
		        }
	        }
	    }

    }

	post {
        always {
			echo "Fin Proceso"
        }
        success {
            echo "Fin OK";
        }
        unstable {
            echo "Fin inestable";
        }
        failure {
            echo "Fin KO";
        }
    }
}
